{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-gradle-plugin",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.8.jar",
          "url": "sjl-gradle-plugin-0.0.8.jar",
          "size": 177457,
          "sha512": "149260bd2f7e5ec65128c44426ca1ca51edb081247d95c1ff38dcf2ea1080e5c1aa9a080d1a514223b1683f8ece53eeb7bf5483fd75daff003cfb58cb38317b4",
          "sha256": "00e22d8f8823df74d40274f8df3d549520f466d55889e6546412f32a0fd4e368",
          "sha1": "5fc67166fb680d54ebbbdfd44e1ad8f66c29b9be",
          "md5": "21bcc10ef727cf1e4eddd62a62d95f29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.gridnine.sjl",
          "module": "sjl-build-tools",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.8.jar",
          "url": "sjl-gradle-plugin-0.0.8.jar",
          "size": 177457,
          "sha512": "149260bd2f7e5ec65128c44426ca1ca51edb081247d95c1ff38dcf2ea1080e5c1aa9a080d1a514223b1683f8ece53eeb7bf5483fd75daff003cfb58cb38317b4",
          "sha256": "00e22d8f8823df74d40274f8df3d549520f466d55889e6546412f32a0fd4e368",
          "sha1": "5fc67166fb680d54ebbbdfd44e1ad8f66c29b9be",
          "md5": "21bcc10ef727cf1e4eddd62a62d95f29"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.8-javadoc.jar",
          "url": "sjl-gradle-plugin-0.0.8-javadoc.jar",
          "size": 261,
          "sha512": "b40fd3bd03310cb0c28bc36f32ea15e007a1975d02492a259a51758c6c082d56b56b72fede2db85611144236f962fd8dccb90fc9d11e6e603da408b41c1b8dde",
          "sha256": "cc505795e2a119b8e5848a57c9dc333cb176269dac088d5248a60d3b02288ae1",
          "sha1": "2ffa1cee7b8685fdba322ad6050fcc5e26301f73",
          "md5": "37fe46f154999e9fb03c6d0c92153ef9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.8-sources.jar",
          "url": "sjl-gradle-plugin-0.0.8-sources.jar",
          "size": 99707,
          "sha512": "922fcdea64899c40d56539337bc2c6ef6742d1cb10d75ec045736c857491bd16220a031ba38cb47358e547e0d474dad625a60014b424ab73038ef99cb6d3094a",
          "sha256": "a0648bbb9b086a821765106deb91c8b330483668740266bfd1949bf2c99d71f8",
          "sha1": "91850cc30c11db416543c4721b1a22b041a8a94a",
          "md5": "2aa8dc645afff7be8d74cabc201cf961"
        }
      ]
    }
  ]
}
