{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-gradle-plugin",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.4.jar",
          "url": "sjl-gradle-plugin-0.0.4.jar",
          "size": 177341,
          "sha512": "67decdd043b4d997c226f1f0b8e05a3f974b895e74698aa155887235945a7707a18259fe1bd89eee509affade08aa2eeb47510ce8531f74469cd495292e947ce",
          "sha256": "d82b5ec276dbefe9206f282ee483b750fc50ff388e6ea062756e505e3c4a90a4",
          "sha1": "2602b68661019f5a3e2a2018064d98d72cdb35f9",
          "md5": "62c9039c090b59a0bafc7a5d8a6c60b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.gridnine.sjl",
          "module": "sjl-build-tools",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.4.jar",
          "url": "sjl-gradle-plugin-0.0.4.jar",
          "size": 177341,
          "sha512": "67decdd043b4d997c226f1f0b8e05a3f974b895e74698aa155887235945a7707a18259fe1bd89eee509affade08aa2eeb47510ce8531f74469cd495292e947ce",
          "sha256": "d82b5ec276dbefe9206f282ee483b750fc50ff388e6ea062756e505e3c4a90a4",
          "sha1": "2602b68661019f5a3e2a2018064d98d72cdb35f9",
          "md5": "62c9039c090b59a0bafc7a5d8a6c60b7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.4-javadoc.jar",
          "url": "sjl-gradle-plugin-0.0.4-javadoc.jar",
          "size": 261,
          "sha512": "7187b81cd7459319f4c18cd9e1022118d9069b9729121836031ca7cc285788ae050c1c164619807b31bd9f7cc138e0ddc4daf19fe109b7939f9f42b9f8d34463",
          "sha256": "4fba56e95ca9247d773ca7bf73110be6e05b1cd8a59bd81a43d9581a1d9b9cbd",
          "sha1": "6faedf1a9cb2f12405ca9b52ca9de79264427e90",
          "md5": "2454770a737071d062a9c0fb6bf3760d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.4-sources.jar",
          "url": "sjl-gradle-plugin-0.0.4-sources.jar",
          "size": 99591,
          "sha512": "0e4e383e8d1b061c4d7aa88db168de927222f7f3d228bb0e44b72bdc3e1f74ec54863f1d556b04871f5c2d36164ecf7f6abcc5cb8bcbeba9b6b9419d3e4a4f46",
          "sha256": "c55eda6219622273f06f8532bf18dbc1a74d63c37d221a5ab217be18f5fd7fa0",
          "sha1": "b00df0a0ae217e6b7fa97c1d6a098b05d5782c56",
          "md5": "bf45665ce5c1a1068f81f9b2969cc3d2"
        }
      ]
    }
  ]
}
