{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-build-tools",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sjl-build-tools-0.0.13.jar",
          "url": "sjl-build-tools-0.0.13.jar",
          "size": 5417729,
          "sha512": "66457b1541f07ce455e02015459e2f20639eb31930017047df80b95136a7e1518fe012c9331ce246b536d241d50f9e2ddff65ed7748a3198160700811c4ac390",
          "sha256": "d721512a5723e6c0a1d6345bb2da5d6efcacc4e01c0b98f8461f120017149f37",
          "sha1": "c35d01524df4da6e556df9819975f68f705c490b",
          "md5": "d79594ca061c154002b4135772362a69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-build-tools-0.0.13.jar",
          "url": "sjl-build-tools-0.0.13.jar",
          "size": 5417729,
          "sha512": "66457b1541f07ce455e02015459e2f20639eb31930017047df80b95136a7e1518fe012c9331ce246b536d241d50f9e2ddff65ed7748a3198160700811c4ac390",
          "sha256": "d721512a5723e6c0a1d6345bb2da5d6efcacc4e01c0b98f8461f120017149f37",
          "sha1": "c35d01524df4da6e556df9819975f68f705c490b",
          "md5": "d79594ca061c154002b4135772362a69"
        }
      ]
    }
  ]
}
