{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-gradle-plugin",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.7.jar",
          "url": "sjl-gradle-plugin-0.0.7.jar",
          "size": 177495,
          "sha512": "eea792af9e17f4efe8c8911dfcd59ac9053fcfdcf9824e502070be9fb58116400a47ed38b1ade2b38f9eb22a5e977af0a919926e7c71f6f9ab94ac3f1ff7aaf0",
          "sha256": "af4ed5eec0198fc75ba25bf6640217c492a9ac00fe376230b76e7325071e433e",
          "sha1": "bdf7f485b47691fd5e213dd74c9b551146e553e7",
          "md5": "92bfb144adaa4f5094cd593045a61a0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.gridnine.sjl",
          "module": "sjl-build-tools",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.7.jar",
          "url": "sjl-gradle-plugin-0.0.7.jar",
          "size": 177495,
          "sha512": "eea792af9e17f4efe8c8911dfcd59ac9053fcfdcf9824e502070be9fb58116400a47ed38b1ade2b38f9eb22a5e977af0a919926e7c71f6f9ab94ac3f1ff7aaf0",
          "sha256": "af4ed5eec0198fc75ba25bf6640217c492a9ac00fe376230b76e7325071e433e",
          "sha1": "bdf7f485b47691fd5e213dd74c9b551146e553e7",
          "md5": "92bfb144adaa4f5094cd593045a61a0b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.7-javadoc.jar",
          "url": "sjl-gradle-plugin-0.0.7-javadoc.jar",
          "size": 261,
          "sha512": "159d0ac8d6892cde844e8f99b42fcbba1eeea350a1f995cefd347ea2b444a92d60ead438b938c2599870124f66a4b2c7acb5167fe40d20c728b1458094024253",
          "sha256": "3c5045c8bdfe465e314bc46315d00f54161aa1033cfeaed613d6d817d23eccc7",
          "sha1": "f815c7dc6330c23e8d87015bfa633d82e7752e0f",
          "md5": "6b0e70adc0e3da1970327862e56d6c3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.7-sources.jar",
          "url": "sjl-gradle-plugin-0.0.7-sources.jar",
          "size": 99745,
          "sha512": "763b876c8cfa391b24ee706d070969861290762df1cef1f052c16d5651b8d444c48a2ce7bfe29c7edb68d3d82c8121613d46e702e48304cf32413ff5a9dde09e",
          "sha256": "7570e6bb6300196617af9d46eaac381a2c6927dfddda871cd54e25abf0d3186a",
          "sha1": "0daefa7a0cee4e858dd2e5c148f539124f8417a7",
          "md5": "2564d64fa24e847909d355c376917207"
        }
      ]
    }
  ]
}
