{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-gradle-plugin",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.10.jar",
          "url": "sjl-gradle-plugin-0.0.10.jar",
          "size": 202850,
          "sha512": "a110d23673176c7da7a436beea61d642d5ba5ec124be1196080b0e871f1a83e964c2b3d976e5a2ef73bd304b970ae32a0a4a22f91d69c7f51e2ad864c5cfdaf3",
          "sha256": "73f2d6437295ddab0118296420c1f40a5c90ae6001ee70ec07e2850d205db567",
          "sha1": "03eaba9760dbff507239e704245c9b59d225e260",
          "md5": "d3c6e18b005432021ca83a6dccc5c92c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.gridnine.sjl",
          "module": "sjl-build-tools",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.10.jar",
          "url": "sjl-gradle-plugin-0.0.10.jar",
          "size": 202850,
          "sha512": "a110d23673176c7da7a436beea61d642d5ba5ec124be1196080b0e871f1a83e964c2b3d976e5a2ef73bd304b970ae32a0a4a22f91d69c7f51e2ad864c5cfdaf3",
          "sha256": "73f2d6437295ddab0118296420c1f40a5c90ae6001ee70ec07e2850d205db567",
          "sha1": "03eaba9760dbff507239e704245c9b59d225e260",
          "md5": "d3c6e18b005432021ca83a6dccc5c92c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.10-javadoc.jar",
          "url": "sjl-gradle-plugin-0.0.10-javadoc.jar",
          "size": 261,
          "sha512": "7b13db36203abd0800928e99d22e3be3e8e75c3547584e140185a82f06036304b31d6b56fecf2150bc78f04abb2b4e104affb7077e04e6e3e336c863f19ed561",
          "sha256": "29b4cd42598180dc27b4e7811fbc13e02af45d4db628099e8293b5cf15507b39",
          "sha1": "68d149aedf0854d64e8fddf1325c22c8222c76f8",
          "md5": "79057de287d5afca12b32939ce94c9a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.10-sources.jar",
          "url": "sjl-gradle-plugin-0.0.10-sources.jar",
          "size": 110899,
          "sha512": "d12060a67e524b6ecac2a8d19f51bac688e23e2a3403ce4d1bb570f851884b0fd66633eb66056bf7de94921e0c1bc352eddcfa2926408528e8e35feafae89dd3",
          "sha256": "caa0fd272a1d64270cbcff608446947c4f8b3a22bcacedf7de2a13ea32de2fd8",
          "sha1": "edbcd25fe5aa1b3ba68d055921c5bc107027c6d0",
          "md5": "14012b6f5b5aa685e952688e86c4f5f1"
        }
      ]
    }
  ]
}
