{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-build-tools",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sjl-build-tools-0.0.8.jar",
          "url": "sjl-build-tools-0.0.8.jar",
          "size": 5417729,
          "sha512": "3fb6645248e0506eacba286b0ae6e08d7f50aa48865df9e921040dfd75cd9c09017000175d9c1bcc4b65beb6b66503cd8a366d14d9d63c66bf5b78659578d08b",
          "sha256": "533040542fbb0d2f6917466ecf08bb54d44373b5ccb62ad327b7de20525fe4d7",
          "sha1": "6cc1aa1b9c9155b3768c150fdfcfdca7db7beb62",
          "md5": "de75f9bd664445b92f8e3c8db5c1c8dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-build-tools-0.0.8.jar",
          "url": "sjl-build-tools-0.0.8.jar",
          "size": 5417729,
          "sha512": "3fb6645248e0506eacba286b0ae6e08d7f50aa48865df9e921040dfd75cd9c09017000175d9c1bcc4b65beb6b66503cd8a366d14d9d63c66bf5b78659578d08b",
          "sha256": "533040542fbb0d2f6917466ecf08bb54d44373b5ccb62ad327b7de20525fe4d7",
          "sha1": "6cc1aa1b9c9155b3768c150fdfcfdca7db7beb62",
          "md5": "de75f9bd664445b92f8e3c8db5c1c8dc"
        }
      ]
    }
  ]
}
