{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-gradle-plugin",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.3.jar",
          "url": "sjl-gradle-plugin-0.0.3.jar",
          "size": 177445,
          "sha512": "51e3fc6c34cf4d85d3c00449076c47a555557b27ae78d5c6098ae112a61880f997c055d51703b6b3b13e796ec6ca147704223a7ce87b12a544b8405d27353cec",
          "sha256": "ffd52e68473f12f46873bcba6152819b9247e3720c0d49ecb75bd039525972eb",
          "sha1": "f12c3f373d0cbe4fdca5eda075c007eb43c7fa36",
          "md5": "9a077e6b6a94f00ec7d595d99aa79477"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.gridnine.sjl",
          "module": "sjl-build-tools",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.3.jar",
          "url": "sjl-gradle-plugin-0.0.3.jar",
          "size": 177445,
          "sha512": "51e3fc6c34cf4d85d3c00449076c47a555557b27ae78d5c6098ae112a61880f997c055d51703b6b3b13e796ec6ca147704223a7ce87b12a544b8405d27353cec",
          "sha256": "ffd52e68473f12f46873bcba6152819b9247e3720c0d49ecb75bd039525972eb",
          "sha1": "f12c3f373d0cbe4fdca5eda075c007eb43c7fa36",
          "md5": "9a077e6b6a94f00ec7d595d99aa79477"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.3-javadoc.jar",
          "url": "sjl-gradle-plugin-0.0.3-javadoc.jar",
          "size": 261,
          "sha512": "24237a807b8f177cd98d7ac1e2c491071d370f558a9dc506de0b299c7a8d39bff4ad1bcbebf1dff9bd706e03275086882f0275f36a0eebcce5c2f44c4b22fa30",
          "sha256": "37fe62e04d48892bfef7b516c6bbdb60846ba0f7c02b76c9037a86b9f22953d5",
          "sha1": "00db1a8b0a4644449b4e336964bc790a6f7792d8",
          "md5": "90d655933e9346f7fe89cc5504345690"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.3-sources.jar",
          "url": "sjl-gradle-plugin-0.0.3-sources.jar",
          "size": 99695,
          "sha512": "49ae7fee9ed440d096bc3c1165b53708eea4a30669f5a03792cfe2eaa86cd246cd43d8dd39a46e5a06d4d1216db87979af746268bfe32521216acfca14f46214",
          "sha256": "4b51cb8370118e3e44084b19580db9ea745279992c88fc438c3cecd7e0adb5fe",
          "sha1": "cc602749d8f8bf13511d3b93fa91fb7b4d28a8cc",
          "md5": "d3b0a2c402ccfab4b042fd32326887d2"
        }
      ]
    }
  ]
}
