{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-gradle-plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.1.jar",
          "url": "sjl-gradle-plugin-0.0.1.jar",
          "size": 177649,
          "sha512": "6e6e6607a687ac857c0943b2699a08b2aa1082ff3816e1ac6653be48aa191225bca5f45c7c7995006f94a2f6eaa986d58df48e59f138758bf38b93687862fce2",
          "sha256": "699c41e9e9a2db2fe61f5eae31b2420a8d2a72f050a86686bb63b652d42325a3",
          "sha1": "21e2512df50aead1e634f4c2fcaaddc480fce3cc",
          "md5": "250c724a2976a8e5c34e9a2521fcc878"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.gridnine.sjl",
          "module": "sjl-build-tools",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.1.jar",
          "url": "sjl-gradle-plugin-0.0.1.jar",
          "size": 177649,
          "sha512": "6e6e6607a687ac857c0943b2699a08b2aa1082ff3816e1ac6653be48aa191225bca5f45c7c7995006f94a2f6eaa986d58df48e59f138758bf38b93687862fce2",
          "sha256": "699c41e9e9a2db2fe61f5eae31b2420a8d2a72f050a86686bb63b652d42325a3",
          "sha1": "21e2512df50aead1e634f4c2fcaaddc480fce3cc",
          "md5": "250c724a2976a8e5c34e9a2521fcc878"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.1-javadoc.jar",
          "url": "sjl-gradle-plugin-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "bf74f97123db3c9033b92826f44971714de52d951663ab075af263f6ecb026e30cb2900937e18753c887b944525d9de59dc545ed9f6294248a84487e7d17eaf8",
          "sha256": "0e8ef0aacfdb06b3facd07956f2c589a385e41b2e71f5c2c9b0f65dd7d9dc526",
          "sha1": "407282002289c35b1b62fa98a265b5939042f9c4",
          "md5": "54532e31a613479b64475db344687b35"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.1-sources.jar",
          "url": "sjl-gradle-plugin-0.0.1-sources.jar",
          "size": 98972,
          "sha512": "618763072e6f625be9e3f939b52793dbb22b00d7f981bfc8d11bb2e61166d6cd39c4b750e48a469f50b49ef299244b5b35c1a79e063224d1fa125030c57c6ed8",
          "sha256": "01429485aa9379334c02d703943fd96aa2fda4c103e20a453218219df9c48e80",
          "sha1": "dd993cab718cce70c077adc7e9c7af38af87465b",
          "md5": "fa4b2259704a5c91349782fceb91cac0"
        }
      ]
    }
  ]
}
