{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-gradle-plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.1.jar",
          "url": "sjl-gradle-plugin-0.0.1.jar",
          "size": 177754,
          "sha512": "1474b3930c67fec8c36a8f956f64e7228fa4eaf25b3a8e0fec11ba1ca4d5f88a026a51e6245c5feefbbfb2200f09f4f86f95be6ad6452d95dffe34a08f0c6697",
          "sha256": "5b9c975143332c770649795bc9f1e29dd451c9216d5ddc7aebedd57af17d5e40",
          "sha1": "4484fa3d62f95bcba456c757e700488491a00c25",
          "md5": "27d31daa61a975865bf6229ee330a72d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.gridnine.sjl",
          "module": "sjl-build-tools",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.1.jar",
          "url": "sjl-gradle-plugin-0.0.1.jar",
          "size": 177754,
          "sha512": "1474b3930c67fec8c36a8f956f64e7228fa4eaf25b3a8e0fec11ba1ca4d5f88a026a51e6245c5feefbbfb2200f09f4f86f95be6ad6452d95dffe34a08f0c6697",
          "sha256": "5b9c975143332c770649795bc9f1e29dd451c9216d5ddc7aebedd57af17d5e40",
          "sha1": "4484fa3d62f95bcba456c757e700488491a00c25",
          "md5": "27d31daa61a975865bf6229ee330a72d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.1-javadoc.jar",
          "url": "sjl-gradle-plugin-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "664b4e16e9c442134c61417fac40a4bb22829d25fbdde1f34831423735a34343e7a8127f53f9cd482d7c45dcd1550f082dab15683622ca01422aa5495d73decb",
          "sha256": "dc9f59e1cca18a2bea56158497bb10ef94d978a7a511ec9c1c6ef7e6ca79aab9",
          "sha1": "4153f76914951d13a579ca2e650c923fab17b449",
          "md5": "9b2232f9060d385104bc8cb1b6cf216f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.1-sources.jar",
          "url": "sjl-gradle-plugin-0.0.1-sources.jar",
          "size": 98969,
          "sha512": "03143d0a6a3a399dc506e48ff63fef4de6c009e18d86ca4b68a389b8ec05664795a90d4eaa668f6875db91d6deb143497b852aba74dd84da25bc0edd80b07996",
          "sha256": "e7ad03a554adf72c23e837db3b10a7b06f4c4d341a2cfba1775c884e44d64f1a",
          "sha1": "61beeab7764c4ebbc48d4dd805c691eab24215aa",
          "md5": "f719c6225240642e72d6c16e1c5e9f75"
        }
      ]
    }
  ]
}
