{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-build-tools",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sjl-build-tools-0.0.1.jar",
          "url": "sjl-build-tools-0.0.1.jar",
          "size": 5417729,
          "sha512": "efdd00a5425d861b2e76541d3dc22c7975ca9ac1acd8af556bb26862c5e7a5d6314eaca34c12ab243e1217650c0ce96f25874c085cbad59360297a4f76da6608",
          "sha256": "20a1af61a0fff1207914c7d6fa3763d830a634e0859f101d7505d1c43d59d48d",
          "sha1": "259283de6993a1b2e331a038697dcbde5e851805",
          "md5": "fd51b35ff1a75598c37f48b9eda456f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-build-tools-0.0.1.jar",
          "url": "sjl-build-tools-0.0.1.jar",
          "size": 5417729,
          "sha512": "efdd00a5425d861b2e76541d3dc22c7975ca9ac1acd8af556bb26862c5e7a5d6314eaca34c12ab243e1217650c0ce96f25874c085cbad59360297a4f76da6608",
          "sha256": "20a1af61a0fff1207914c7d6fa3763d830a634e0859f101d7505d1c43d59d48d",
          "sha1": "259283de6993a1b2e331a038697dcbde5e851805",
          "md5": "fd51b35ff1a75598c37f48b9eda456f3"
        }
      ]
    }
  ]
}
