{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-build-tools",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sjl-build-tools-0.0.1.jar",
          "url": "sjl-build-tools-0.0.1.jar",
          "size": 5417729,
          "sha512": "28aef76e8fe63bd382260ef410300e7ebc49df0ead4ba7c0219d0f431dace2247ac1144d4176a252c42a755a24fcf4700e1adc030e5aeaf316f7660ad262949d",
          "sha256": "a5076690ff5cdfe8f39335f2a29d1ed835ecc8eee26125248daf1d9a5a5d7b47",
          "sha1": "a8df8cb3978320ef948067aeb979803b355e7372",
          "md5": "fac864ec1405be3fcb1b15bf3558621d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-build-tools-0.0.1.jar",
          "url": "sjl-build-tools-0.0.1.jar",
          "size": 5417729,
          "sha512": "28aef76e8fe63bd382260ef410300e7ebc49df0ead4ba7c0219d0f431dace2247ac1144d4176a252c42a755a24fcf4700e1adc030e5aeaf316f7660ad262949d",
          "sha256": "a5076690ff5cdfe8f39335f2a29d1ed835ecc8eee26125248daf1d9a5a5d7b47",
          "sha1": "a8df8cb3978320ef948067aeb979803b355e7372",
          "md5": "fac864ec1405be3fcb1b15bf3558621d"
        }
      ]
    }
  ]
}
