{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-gradle-plugin",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.13.jar",
          "url": "sjl-gradle-plugin-0.0.13.jar",
          "size": 203355,
          "sha512": "e1500b02e236ac5bbeb619ef15021759678b08b30aee0642d4a61d7b92b57fb162d2f25a45f0354c97f3854ad5d1e0b4150b41521f5a4fb4653045eac4254df9",
          "sha256": "8be23a3fd9ef55d3c2b87edf4a5ea1dcbb80d8c4f35dcee825f40626b5f12575",
          "sha1": "af69adc603cabe2e52b9e2068b0289132f8849ae",
          "md5": "8f4e261096405e3401377d66ffdb3005"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.gridnine.sjl",
          "module": "sjl-build-tools",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.13.jar",
          "url": "sjl-gradle-plugin-0.0.13.jar",
          "size": 203355,
          "sha512": "e1500b02e236ac5bbeb619ef15021759678b08b30aee0642d4a61d7b92b57fb162d2f25a45f0354c97f3854ad5d1e0b4150b41521f5a4fb4653045eac4254df9",
          "sha256": "8be23a3fd9ef55d3c2b87edf4a5ea1dcbb80d8c4f35dcee825f40626b5f12575",
          "sha1": "af69adc603cabe2e52b9e2068b0289132f8849ae",
          "md5": "8f4e261096405e3401377d66ffdb3005"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.13-javadoc.jar",
          "url": "sjl-gradle-plugin-0.0.13-javadoc.jar",
          "size": 261,
          "sha512": "7b1cf751260bf721fcaec1ac0c79f535cd043dedb9efa4eb4fee3947d3b09350b3763aea2d145c09b89b6acd005929adb575a1aee1b958b85e5b85dec95ab948",
          "sha256": "f5f0498d207f84e4f3f4e89529e87b7bbefdb9630212379bb0f93532c4240259",
          "sha1": "9d5822d9e221b7cd5280be5275c592b51e83de57",
          "md5": "52a570cb9fa7442ab195fb85c1266c22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.13-sources.jar",
          "url": "sjl-gradle-plugin-0.0.13-sources.jar",
          "size": 111316,
          "sha512": "f7ff579dce13b0aa7a9e16959267aff30c557c9535c4f83e84a2227686f8f6d3769231e10340b0eea87e92669b505387fc274295a3d9049ea1b5c61f377bf7a3",
          "sha256": "8ea25bebad46805d6ea8e7ba34fd532ccea0c20e5a73f86506514c8ada361e3d",
          "sha1": "3279b1468031767ee22000741747aa8e815a1d2e",
          "md5": "19db1492b162720c341369dd8291cf06"
        }
      ]
    }
  ]
}
