{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-gradle-plugin",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.13.jar",
          "url": "sjl-gradle-plugin-0.0.13.jar",
          "size": 203553,
          "sha512": "4f1d16190bc31d95fdb1d0883468171f3673e63e2dfcd79a06597088e0b7084b49dbee13a422ab6083a17ba0152de6554b34975d1ec569576aac0f3f722f0114",
          "sha256": "2fc6822bfae0407b25728701630de2385baf58fe67753e96abe321659067c56e",
          "sha1": "6e9e9604105e77870b316cf7470daedc28c6dc8f",
          "md5": "b458925847a2f1e1e4e221e9e727ef1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.gridnine.sjl",
          "module": "sjl-build-tools",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.13.jar",
          "url": "sjl-gradle-plugin-0.0.13.jar",
          "size": 203553,
          "sha512": "4f1d16190bc31d95fdb1d0883468171f3673e63e2dfcd79a06597088e0b7084b49dbee13a422ab6083a17ba0152de6554b34975d1ec569576aac0f3f722f0114",
          "sha256": "2fc6822bfae0407b25728701630de2385baf58fe67753e96abe321659067c56e",
          "sha1": "6e9e9604105e77870b316cf7470daedc28c6dc8f",
          "md5": "b458925847a2f1e1e4e221e9e727ef1a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.13-javadoc.jar",
          "url": "sjl-gradle-plugin-0.0.13-javadoc.jar",
          "size": 261,
          "sha512": "7b1cf751260bf721fcaec1ac0c79f535cd043dedb9efa4eb4fee3947d3b09350b3763aea2d145c09b89b6acd005929adb575a1aee1b958b85e5b85dec95ab948",
          "sha256": "f5f0498d207f84e4f3f4e89529e87b7bbefdb9630212379bb0f93532c4240259",
          "sha1": "9d5822d9e221b7cd5280be5275c592b51e83de57",
          "md5": "52a570cb9fa7442ab195fb85c1266c22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.13-sources.jar",
          "url": "sjl-gradle-plugin-0.0.13-sources.jar",
          "size": 111514,
          "sha512": "f2bdc75c23d8b2f6fa88b984406810318832038ab4d63969a83f177916074bceece5cc2d4daddb75c49a0bdabefd27e20d61c1be79fcd8dad972f8c1c925f2e8",
          "sha256": "d86acf68d4e5f901039eb10f6379fbcdbd237fe4965bfc89e9c933adc813108f",
          "sha1": "045c4a0674b2de3618f2c5d66d36d79195424601",
          "md5": "df879fcba018ce0c8be341a993611a52"
        }
      ]
    }
  ]
}
