{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-gradle-plugin",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.12.jar",
          "url": "sjl-gradle-plugin-0.0.12.jar",
          "size": 203344,
          "sha512": "ae5b5fa9f251ecb967fc999a18dc241fd131256ac83030c9afc5b4b302f91b800fafde86d9cf6ed948927ceb771d2e0fa8c8251ab98cf681a6e11db1b16dff2b",
          "sha256": "e6e3912390110035991c34bd9b29468ae48a75d31473b6b8bb94f203440de609",
          "sha1": "b58315eb4d34a2da8a70f5fc7c661a350f2874d6",
          "md5": "b7800993151eef30da7aa6e956befec1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.gridnine.sjl",
          "module": "sjl-build-tools",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.12.jar",
          "url": "sjl-gradle-plugin-0.0.12.jar",
          "size": 203344,
          "sha512": "ae5b5fa9f251ecb967fc999a18dc241fd131256ac83030c9afc5b4b302f91b800fafde86d9cf6ed948927ceb771d2e0fa8c8251ab98cf681a6e11db1b16dff2b",
          "sha256": "e6e3912390110035991c34bd9b29468ae48a75d31473b6b8bb94f203440de609",
          "sha1": "b58315eb4d34a2da8a70f5fc7c661a350f2874d6",
          "md5": "b7800993151eef30da7aa6e956befec1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.12-javadoc.jar",
          "url": "sjl-gradle-plugin-0.0.12-javadoc.jar",
          "size": 261,
          "sha512": "195122bfa7e3fc1e3368a67c8690017364673547a088b1cc79fdeec573db129f8cc4fafc9fda50989128e29e3c025ce83ba3e437d3de95f3da5c4a0006720f2a",
          "sha256": "46654dcb7ba560ee31385d2da813b17980a426f79f5aac3c0bdc1f41de5cb122",
          "sha1": "435a4948cb8bc552318901023e5ee9e550607ff2",
          "md5": "8bf7defe5315a681b610e68493328420"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-gradle-plugin-0.0.12-sources.jar",
          "url": "sjl-gradle-plugin-0.0.12-sources.jar",
          "size": 111389,
          "sha512": "d2658a4df135a0e2f6c72313aa4dd9204f06d9f4ffb0e7c8fc61732c70a4f324c93f5d7d716ddb8bebfea9657e3085427070b40fb7f70d070551f8b042550bc0",
          "sha256": "eac0f0f538333a0da1d23518afaaff9ee7535e5c73fcdec8c4567850419dfb33",
          "sha1": "ee708b75c5b5cd95de39b64119bac234ed47bf30",
          "md5": "6a0beebb10940e7812e8c1ab2eb4aff4"
        }
      ]
    }
  ]
}
