{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine.sjl",
    "module": "sjl-build-tools",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sjl-build-tools-0.0.9.jar",
          "url": "sjl-build-tools-0.0.9.jar",
          "size": 5417729,
          "sha512": "a23abd03db8fe2751177bbef7de9832a2cd129e5e1322f52617a5d22bd5876ba28780a8408f88266523a7e5a4df5cd66dc305e995f27dc2b425b47e05a5dc04d",
          "sha256": "de8d313087476de22352115a4a7f57106da15b3707ea95965004c203c5a5fa56",
          "sha1": "1adfb4ac9ce0a44f2bbf7586e7d6919656defe53",
          "md5": "ce604014824d58408ffea67ecd214bfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sjl-build-tools-0.0.9.jar",
          "url": "sjl-build-tools-0.0.9.jar",
          "size": 5417729,
          "sha512": "a23abd03db8fe2751177bbef7de9832a2cd129e5e1322f52617a5d22bd5876ba28780a8408f88266523a7e5a4df5cd66dc305e995f27dc2b425b47e05a5dc04d",
          "sha256": "de8d313087476de22352115a4a7f57106da15b3707ea95965004c203c5a5fa56",
          "sha1": "1adfb4ac9ce0a44f2bbf7586e7d6919656defe53",
          "md5": "ce604014824d58408ffea67ecd214bfc"
        }
      ]
    }
  ]
}
